# Generated by Django 4.1.3 on 2022-12-21 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realtor',
            name='image',
        ),
    ]
