# Generated by Django 4.1.3 on 2022-12-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0002_remove_realtor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='image',
            field=models.ImageField(default=1, upload_to='photos/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
