# Generated by Django 4.1.3 on 2022-12-21 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0003_realtor_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realtor',
            old_name='image',
            new_name='photo',
        ),
    ]
